### ISSUE TITLE
Is there bug in test script?

### ISSUE THREAD

**Issue by liyi193328** [chen3feng/blade-build#431]
when I run src/test/swig_library_test.py
error is:
Traceback (most recent call last):
  File "~/typhoon-blade/src/test/swig_library_test.py", line 26, in testGenerateRules
    self.rules_buf = self.blade.generate_build_rules()
  File "../blade/blade.py", line 133, in generate_build_rules
    rules = generator.generate_build_script()
  File "../blade/rules_generator.py", line 840, in generate_build_script
    rules = self.generate_build_rules()
  File "../blade/rules_generator.py", line 866, in generate_build_rules
    rules = self.scons_script_header_generator.generate(self.blade_path)
  File "../blade/rules_generator.py", line 377, in generate
    self.generate_compliation_verbose()
  File "../blade/rules_generator.py", line 138, in generate_compliation_verbose
    (console.color_enabled, self.options.verbosity))
AttributeError: 'Namespace' object has no attribute 'verbosity'

======================================================================
FAIL: testLoadBuildsNotNone (__main__.TestSwigLibrary)
Test direct targets and all command targets are not none.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/turingli/software/typhoon-blade/src/test/blade_test.py", line 85, in testLoadBuildsNotNone
    self.assertTrue(self.all_command_targets)
AssertionError: [] is not true

----------------------------------------------------------------------
Ran 2 tests in 0.976s

FAILED (failures=1, errors=1)

Is there any bug?

**Comment by chen3feng** [comment]
Maybe. I'm planning to upgrade test to be true unit tests(class/function level) and use blade to build blade it self.

**Comment by chen3feng** [comment]
Fixed in #616
