### ISSUE TITLE
items  in "hdr_dep_missing_suppress.conf" need to strongly ordered?

### ISSUE THREAD

**Issue by kuafu-run** [chen3feng/blade-build#958]
i have my BLADE_ROOT config as follows：
cc_config (
......
hdr_dep_missing_severity = 'error',
hdr_dep_missing_suppress = load_value('blade_helper/hdr_dep_missing_suppress.conf'),
allowed_undeclared_hdrs = load_value('blade_helper/allowed_undeclared_hdrs.conf'),
)
and initially i use:
blade-build-2.0-beta2/tool/collect-inclusion-errors.py --missing | tee blade_helper/hdr_dep_missing_suppress.conf
blade-build-2.0-beta2/tool/collect-inclusion-errors.py --undeclared | tee blade_helper/allowed_undeclared_hdrs.conf
to generate hdr_dep_missing_suppress.conf and allowed_undeclared_hdrs.conf

but other team-members are not aware of this tool, they change these two conf files **manually**!!!
the contents are legal，a list and dictionary of python，but not ordered as the output of the tool.

as time goes, project not working well when run blade build ./...
and print "assert level == current_level + 1" **randomly**， here is an example:

[3897/6946] CXX ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.cpp
build64_release/ads/proto/enums/creative_screen_type.pb.h
/usr/include/google/protobuf/port_undef.inc
/usr/include/boost/date_time/date_generator_formatter.hpp
/usr/include/google/protobuf/port_def.inc
/usr/include/boost/container/detail/config_end.hpp
/usr/include/bits/fcntl.h
/usr/include/boost/interprocess/detail/config_end.hpp
/usr/include/boost/interprocess/detail/config_begin.hpp
/usr/include/boost/assert.hpp
/usr/include/boost/container/detail/destroyers.hpp
/usr/include/boost/type_traits/has_greater.hpp
/usr/include/boost/type_traits/detail/bool_trait_undef.hpp
/usr/include/boost/range/distance.hpp
/usr/include/boost/concept/usage.hpp
/usr/include/boost/preprocessor/seq/elem.hpp
/usr/include/google/protobuf/port_undef.inc
/usr/include/google/protobuf/port_undef.inc
[3898/6946] CXX ads/serving/exchange/handler/redis_service.cpp
[3899/6946] CC INCLUSION CHECK build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk
FAILED: build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk.result
PYTHONPATH=/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src:$PYTHONPATH /usr/bin/python -m blade.builtin_tools cc_inclusion_check build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk.result build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk
Blade(error): Blade build tool cc_inclusion_check error: Traceback (most recent call last):
File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/builtin_tools.py", line 599, in main
exit_code = _BUILTIN_TOOLS[name](args=args, **options)
File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/builtin_tools.py", line 117, in generate_cc_inclusion_check
ok, details = inclusion_check.check(info_file)
File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 399, in check
return checker.check()
File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 371, in check
check_file(src, full_src, is_header=False)
File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 352, in check_file
direct_hdrs, stacks = _parse_inclusion_stacks(path, self.build_dir)
File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 132, in _parse_inclusion_stacks
assert level == current_level + 1
AssertionError

**Comment by kuafu-run** [comment]
here is another example：

[root@003-12c58f78d ads_serving]# PYTHONPATH=/data/code/ads_serving/blade-build-2.0-beta2/src:$PYTHONPATH /usr/bin/python -m blade.builtin_tools cc_inclusion_check build64_release/ads/serving/dsp_recommend_show/show_handler.incchk.result build64_release/ads/serving/dsp_recommend_show/show_handler.incchk
Blade(error): Blade build tool cc_inclusion_check error:  Traceback (most recent call last):
  File "/data/code/ads_serving/blade-build-2.0-beta2/src/blade/builtin_tools.py", line 599, in main
    exit_code = _BUILTIN_TOOLS[name](args=args, **options)
  File "/data/code/ads_serving/blade-build-2.0-beta2/src/blade/builtin_tools.py", line 117, in generate_cc_inclusion_check
    ok, details = inclusion_check.check(info_file)
  File "/data/code/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 399, in check
    return checker.check()
  File "/data/code/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 371, in check
    check_file(src, full_src, is_header=False)
  File "/data/code/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 352, in check_file
    direct_hdrs, stacks = _parse_inclusion_stacks(path, self.build_dir)
  File "/data/code/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 132, in _parse_inclusion_stacks
    assert level == current_level + 1
AssertionError

here is the .incchk file， don't know how it is generated
[show_handler.incchk.txt](https://github.com/chen3feng/blade-build/files/7076636/show_handler.incchk.txt)
